### ISSUE TITLE
Remove Level 8

### ISSUE THREAD

**Issue by hhirsch** [lightly-io/starting-meditation#10]
https://www.reddit.com/r/Buddhism/comments/7awsku/buddhadharmaorg_is_a_free_open_source_site/dpduell/

@mattisern I would like to remove this Line if it is ok with you.

**Comment by mattisern** [comment]
It's a bit tongue-in-cheek and not critical to the website, so I'm OK with removing it. But I do think that striving for "that special place" is counter-productive to this practice. The more I've met people who claim they've been enlightened, the more I've become sceptical ...

**Comment by hhirsch** [comment]
@mattisern I totally agree and I think the guide will benefit from having something in there that reminds people of not focusing on enlightenment too much. It just has to be phrased a bit differently.

Addressing that in #12
